blog_blog:
    resource: "@BlogBundle/Resources/config/routing/blog.yml"
    prefix:   /blog

blog_homepage:
    #path:     /
    pattern: /
    defaults: { _controller: BlogBundle:Page:index }
    requirements:
        _method: GET

blog_show:
    pattern:  /{id}
    defaults: { _controller: BlogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+